import { PDFDocument } from 'pdf-lib';
import { describe, expect, it, vi } from 'vitest';
import { buildExportFileName, downloadPdfBytes, generateBookletPdfBytes } from './pdf';
import type { BookletSheet } from '../../lib/booklet';
import type { PreviewAsset } from '../preview';
import type { ZinePage } from '../../types';

const onePixelPngBase64 =
  'iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mP8/x8AAukB9VE3dRkAAAAASUVORK5CYII=';

function makeAsset(id: string, fileName: string): PreviewAsset {
  return {
    id,
    file: new File([Uint8Array.from(atob(onePixelPngBase64), (char) => char.charCodeAt(0))], fileName, {
      type: 'image/png',
    }),
    fileName,
    format: 'image/png',
    previewUrl: `blob:${fileName}`,
    rotationQuarterTurns: 0,
  };
}

function makePage(pageNumber: number, assetId: string | null): ZinePage {
  const role =
    pageNumber === 1 ? 'front-cover' : pageNumber === 4 ? 'back-cover' : assetId ? 'body' : 'blank';
  const layoutId = assetId ? (pageNumber === 1 || pageNumber === 4 ? 'cover-full' : 'single-portrait') : 'blank';

  return {
    id: `page-${pageNumber}`,
    pageNumber,
    role,
    layoutId,
    spreadId: null,
    locked: false,
    frames: assetId
      ? [
          {
            id: `page-${pageNumber}-frame-1`,
            pageId: `page-${pageNumber}`,
            assetId,
            slotIndex: 0,
            x: 0.1,
            y: 0.1,
            width: 0.8,
            height: 0.8,
            fitMode: 'contain' as const,
            rotationQuarterTurns: 0 as const,
          },
        ]
      : [],
    sourceAssetIds: assetId ? [assetId] : [],
    background: 'white' as const,
    plannerNote: null,
  };
}

function makeSheet(): BookletSheet {
  return {
    id: 'sheet-1',
    sheetNumber: 1,
    front: {
      id: 'sheet-1-front',
      sheetNumber: 1,
      side: 'front',
      leftPage: makePage(4, null),
      rightPage: makePage(1, 'cover'),
    },
    back: {
      id: 'sheet-1-back',
      sheetNumber: 1,
      side: 'back',
      leftPage: makePage(2, 'body-a'),
      rightPage: makePage(3, 'body-b'),
    },
  };
}

describe('PDF export', () => {
  it('generates one landscape A4 PDF page per imposed sheet side', async () => {
    const assetMap = {
      cover: makeAsset('cover', 'cover.png'),
      'body-a': makeAsset('body-a', 'body-a.png'),
      'body-b': makeAsset('body-b', 'body-b.png'),
    };

    const bytes = await generateBookletPdfBytes([makeSheet()], assetMap);
    const pdfDocument = await PDFDocument.load(bytes);

    expect(pdfDocument.getPageCount()).toBe(2);
    expect(pdfDocument.getPage(0)?.getSize().width).toBeCloseTo(841.89, 1);
    expect(pdfDocument.getPage(0)?.getSize().height).toBeCloseTo(595.28, 1);
  });

  it('uses a stable default export file name', () => {
    expect(buildExportFileName()).toBe('photo-zine-booklet.pdf');
  });

  it('downloads generated bytes as a PDF file', () => {
    Object.defineProperty(URL, 'createObjectURL', {
      writable: true,
      value: vi.fn(),
    });
    Object.defineProperty(URL, 'revokeObjectURL', {
      writable: true,
      value: vi.fn(),
    });

    const createObjectUrl = vi
      .spyOn(URL, 'createObjectURL')
      .mockReturnValue('blob:download-pdf');
    const revokeObjectUrl = vi.spyOn(URL, 'revokeObjectURL').mockReturnValue();
    const click = vi
      .spyOn(HTMLAnchorElement.prototype, 'click')
      .mockImplementation(() => undefined);

    downloadPdfBytes(new Uint8Array([1, 2, 3]), 'test.pdf');

    expect(createObjectUrl).toHaveBeenCalledTimes(1);
    expect(revokeObjectUrl).toHaveBeenCalledWith('blob:download-pdf');
    expect(click).toHaveBeenCalledTimes(1);
  });
});
